import 'package:flutter_test/flutter_test.dart';
import 'package:odoo_sdk/odoo_sdk.dart' show SRIKeyGenerator;

void main() {
  group('SRIKeyGenerator', () {
    test('matches native Odoo l10n_ec_edi fiscal keys exactly', () {
      // Generated by executing the unmodified method bodies from this stack's
      // enterprise/l10n_ec_edi/models/account_move.py:
      // _l10n_ec_set_authorization_number and _l10n_ec_get_check_digit.
      // Include both environments and check digits 0, 1 and 9.
      const vectors = [
        ('1', 1, '0509202601179001122300110010020000000013121521410'),
        ('1', 3, '0509202601179001122300110010020000000033121521411'),
        ('1', 8, '0509202601179001122300110010020000000083121521419'),
        ('2', 1, '0509202601179001122300120010020000000013121521419'),
        ('2', 3, '0509202601179001122300120010020000000033121521411'),
        ('2', 5, '0509202601179001122300120010020000000053121521410'),
      ];
      for (final (environment, sequence, expected) in vectors) {
        expect(
          SRIKeyGenerator.generateAccessKey(
            date: DateTime(2026, 9, 5),
            documentType: '01',
            ruc: '1790011223001',
            environment: environment,
            invoiceName: SRIKeyGenerator.generateInvoiceName(
              entity: '001',
              emission: '002',
              sequence: sequence,
            ),
            emissionType: '1',
          ),
          expected,
        );
      }
    });

    test('generateAccessKey creates valid 49 digit key', () {
      final key = SRIKeyGenerator.generateAccessKey(
        date: DateTime(2023, 12, 25),
        documentType: '01', // Factura
        ruc: '1790011223001',
        environment: '1', // Pruebas
        invoiceName: '001-001-000000001',
        emissionType: '1', // Normal
      );

      expect(key, hasLength(49));
      expect(RegExp(r'^\d+$').hasMatch(key), isTrue);

      // Verify structure
      // Fecha: 25122023 (8)
      expect(key.substring(0, 8), '25122023');
      // Tipo Comprobante: 01 (2)
      expect(key.substring(8, 10), '01');
      // RUC: 1790011223001 (13)
      expect(key.substring(10, 23), '1790011223001');
      // Environment: 1 (1)
      expect(key.substring(23, 24), '1');
      // Serie: 001001 (6)
      expect(key.substring(24, 30), '001001');
      // Secuencia: 000000001 (9)
      expect(key.substring(30, 39), '000000001');
      // Codigo Numerico: 12345678 (8) - calculated internally, but we check position
      // Emission Type: 1 (1)
      expect(key.substring(47, 48), '1');
      // Check Digit: (1) - last char
    });

    test('module 11 check digit calculation is correct', () {
      // Example from SRI documentation (if available) or verified example
      // Using a constructed example where we can verify the check digit calculation logic manually if needed
      // or relying on the generator's internal consistency.

      // Let's test consistent generation
      final key1 = SRIKeyGenerator.generateAccessKey(
        date: DateTime(2023, 10, 01),
        documentType: '01',
        ruc: '1792049504001',
        environment: '1',
        invoiceName: '001-001-000000123',
        emissionType: '1',
      );

      final checkDigit = key1.substring(48, 49);

      // We can't easily access the private _computeModule11, but we can verify the key is valid structure
      expect(int.tryParse(checkDigit), isNotNull);
    });

    test('generateInvoiceName formats correctly', () {
      final name = SRIKeyGenerator.generateInvoiceName(
        entity: '001',
        emission: '002',
        sequence: 123,
      );

      expect(name, '001-002-000000123');
    });

    test('generateInvoiceName formats correctly with large sequence', () {
      final name = SRIKeyGenerator.generateInvoiceName(
        entity: '001',
        emission: '002',
        sequence: 123456789,
      );

      expect(name, '001-002-123456789');
    });
  });
}
