/// SmartOdooModel - Reactive Model Base with Computed Fields
///
/// Extends OdooRecord with Odoo-like reactive capabilities:
/// - Computed fields that auto-recalculate when dependencies change
/// - Onchange methods triggered by field changes
/// - Constraint validation on specific fields
/// - State machine transitions
/// - Line item management with automatic total recalculation
/// - Integrated sync and WebSocket handling (Matrix pattern)
///
/// ## Matrix Pattern
///
/// The SmartOdooModel implements the "Matrix" pattern - a single object that
/// encapsulates ALL model behavior:
/// - Field definitions with types
/// - Automatic computed field calculation
/// - Validation rules
/// - State machine transitions
/// - Sync configuration
/// - WebSocket event handling
///
/// ## Usage
///
/// ```dart
/// @OdooModel('sale.order')
/// @OdooStateMachine(
///   stateField: 'state',
///   transitions: {
///     'draft': ['sent', 'cancel'],
///     'sent': ['sale', 'draft', 'cancel'],
///     'sale': ['done', 'cancel'],
///   },
/// )
/// @freezed
/// class SaleOrder with _$SaleOrder, SmartOdooModel<SaleOrder> {
///   const SaleOrder._();
///
///   // Static configuration (Matrix metadata)
///   static SmartModelConfig get config => SmartModelConfig(
///     odooModel: 'sale.order',
///     tableName: 'sale_orders',
///     syncConfig: SyncConfig.realtime(),
///     fieldDefinitions: [
///       FieldBuilder.char('name').isRequired().build(),
///       FieldBuilder.selection('state', {...}).build(),
///       FieldBuilder.monetary('amountTotal')
///         .depends(['orderLines.priceSubtotal'])
///         .compute('_computeAmounts')
///         .build(),
///     ],
///   );
///
///   const factory SaleOrder({
///     @OdooId() required int id,
///     @OdooMany2One('res.partner') int? partnerId,
///     @OdooStoredComputed(
///       depends: ['orderLines.priceSubtotal'],
///       compute: '_computeAmounts',
///     )
///     @Default(0.0) double amountTotal,
///     @OdooOne2Many('sale.order.line', inverseField: 'orderId')
///     @Default([]) List<SaleOrderLine> orderLines,
///   }) = _SaleOrder;
///
///   // Compute method
///   Map<String, dynamic> _computeAmounts() {
///     final total = orderLines.fold(0.0, (sum, l) => sum + l.priceSubtotal);
///     return {'amountTotal': total};
///   }
///
///   // Onchange method
///   SaleOrder _onchangePartnerId(Client? partner) {
///     return copyWith(paymentTermId: partner?.propertyPaymentTermId);
///   }
/// }
/// ```
library;

import 'computed_field_engine.dart';
import 'field_definition.dart';
import 'odoo_model_manager.dart';
import 'odoo_record.dart';
import 'smart_model_config.dart';

/// Mixin that provides reactive computed fields and onchange behavior.
///
/// Models using this mixin get:
/// - [recompute] - Recalculate computed fields when dependencies change
/// - [onFieldChanged] - Execute onchange handlers when fields change
/// - [updateField] - Update a field and trigger recomputation
/// - [addLine] / [updateLine] / [removeLine] - Manage One2many lines
///
/// The generated code (via build_runner) provides:
/// - Dependency graph for computed fields
/// - Dispatch for onchange methods
/// - Type-safe field update methods
///
/// **Note:** This mixin requires OdooRecord to be mixed in first.
mixin SmartOdooModel<T extends SmartOdooModel<T>> on OdooRecord<T> {
  /// Access the model manager via the global registry.
  OdooModelManager<T> get _managerRef {
    final manager = OdooRecordRegistry.get<T>();
    if (manager == null) {
      throw StateError(
        'No manager registered for ${T.toString()}. '
        'Call OdooRecordRegistry.register<$T>(manager) first.',
      );
    }
    return manager;
  }

  // ═══════════════════════════════════════════════════════════════════════════
  // Computed Fields - Override in generated code
  // ═══════════════════════════════════════════════════════════════════════════

  /// Dependency graph: field -> list of computed fields that depend on it.
  ///
  /// Generated by build_runner from @OdooStoredComputed annotations.
  ///
  /// Example:
  /// ```dart
  /// static const _dependencyGraph = {
  ///   'orderLines': ['amountUntaxed', 'amountTax', 'amountTotal'],
  ///   'priceUnit': ['priceSubtotal', 'priceTotal'],
  /// };
  /// ```
  Map<String, List<String>> get dependencyGraph => const {};

  /// Recalculate computed fields that depend on [changedField].
  ///
  /// Returns a new instance with updated computed values.
  /// Call this after modifying a field that other fields depend on.
  ///
  /// ```dart
  /// final updated = order.copyWith(orderLines: newLines).recompute('orderLines');
  /// // amountTotal, amountTax, etc. are now recalculated
  /// ```
  T recompute(String changedField) {
    // Default implementation - override in generated code
    return this as T;
  }

  /// Recompute multiple fields at once.
  ///
  /// More efficient than calling recompute multiple times.
  T recomputeAll(Set<String> changedFields) {
    var result = this as T;
    for (final field in changedFields) {
      result = result.recompute(field);
    }
    return result;
  }

  /// Force recalculation of all computed fields.
  ///
  /// Useful after loading from database or when dependencies might be stale.
  T recomputeAllFields() {
    // Default implementation - override in generated code
    return this as T;
  }

  // ═══════════════════════════════════════════════════════════════════════════
  // Onchange Handlers - Override in generated code
  // ═══════════════════════════════════════════════════════════════════════════

  /// Map of field -> onchange method name.
  ///
  /// Generated by build_runner from @OdooOnchange annotations.
  Map<String, String> get onchangeHandlers => _managerRef.onchangeHandlerMap;

  /// Execute onchange handler for [field] with [newValue].
  ///
  /// Returns a new instance with fields updated by the onchange logic.
  /// Typically called after user input changes a field value.
  ///
  /// ```dart
  /// final updated = order.onFieldChanged('partnerId', newPartnerId);
  /// // paymentTermId, pricelistId, etc. may be updated by onchange
  /// ```
  T onFieldChanged(String field, dynamic newValue) =>
      _managerRef.dispatchOnchange(this as T, field, newValue);

  /// Update a field value and execute any related onchange handlers.
  ///
  /// Combines copyWith + onchange + recompute in one operation.
  /// This is the preferred way to update fields in the UI.
  ///
  /// ```dart
  /// final updated = order.updateField('partnerId', newPartnerId);
  /// // 1. partnerId is updated
  /// // 2. _onchangePartnerId is called
  /// // 3. Computed fields depending on partnerId are recalculated
  /// ```
  T updateField(String field, dynamic value) {
    // This would be implemented by generated code with proper dispatch
    return onFieldChanged(field, value);
  }

  // ═══════════════════════════════════════════════════════════════════════════
  // One2many Line Management
  // ═══════════════════════════════════════════════════════════════════════════

  /// Add a line to a One2many field and recalculate totals.
  ///
  /// Override in your model to implement line management.
  /// This default implementation returns the unchanged model.
  ///
  /// ```dart
  /// final newLine = SaleOrderLine(productId: 1, quantity: 5);
  /// final updated = order.addLine('orderLines', newLine);
  /// ```
  T addLine<L>(String field, L line) {
    // Default: no-op - override to implement line management
    return this as T;
  }

  /// Update a line in a One2many field and recalculate totals.
  ///
  /// Override in your model to implement line management.
  /// This default implementation returns the unchanged model.
  ///
  /// ```dart
  /// final updatedLine = order.orderLines[0].copyWith(quantity: 10);
  /// final updated = order.updateLine('orderLines', 0, updatedLine);
  /// ```
  T updateLine<L>(String field, int index, L line) {
    // Default: no-op - override to implement line management
    return this as T;
  }

  /// Remove a line from a One2many field and recalculate totals.
  ///
  /// Override in your model to implement line management.
  /// This default implementation returns the unchanged model.
  ///
  /// ```dart
  /// final updated = order.removeLine('orderLines', 0);
  /// ```
  T removeLine(String field, int index) {
    // Default: no-op - override to implement line management
    return this as T;
  }

  /// Replace all lines in a One2many field and recalculate totals.
  ///
  /// Override in your model to implement line management.
  /// This default implementation returns the unchanged model.
  ///
  /// ```dart
  /// final updated = order.setLines('orderLines', newLinesList);
  /// ```
  T setLines<L>(String field, List<L> lines) {
    // Default: no-op - override to implement line management
    return this as T;
  }

  // ═══════════════════════════════════════════════════════════════════════════
  // State Machine
  // ═══════════════════════════════════════════════════════════════════════════

  /// Get current state value.
  ///
  /// Delegates to manager's stateField to look up the value dynamically.
  String? get currentState => _managerRef.stateField != null
      ? _getFieldValue(_managerRef.stateField!) as String?
      : null;

  /// State transitions map: state -> list of allowed next states.
  ///
  /// Generated from @OdooStateMachine annotation.
  Map<String, List<String>> get stateTransitions => _managerRef.stateTransitionMap;

  /// Check if transition from current state to [targetState] is allowed.
  bool canTransitionTo(String targetState) {
    final current = currentState;
    if (current == null) return true;
    final allowed = stateTransitions[current];
    return allowed?.contains(targetState) ?? false;
  }

  /// Get list of allowed next states from current state.
  List<String> get allowedTransitions {
    final current = currentState;
    if (current == null) return [];
    return stateTransitions[current] ?? [];
  }

  /// Validate state transition before action.
  ///
  /// Throws [StateError] if transition not allowed.
  void ensureCanTransitionTo(String targetState) {
    if (!canTransitionTo(targetState)) {
      throw StateError(
        'Cannot transition from "$currentState" to "$targetState". '
        'Allowed: ${allowedTransitions.join(", ")}',
      );
    }
  }

  // ═══════════════════════════════════════════════════════════════════════════
  // Constraint Validation
  // ═══════════════════════════════════════════════════════════════════════════

  /// Map of constraint names to field lists.
  ///
  /// Generated from @OdooConstraint annotations.
  Map<String, List<String>> get constraintFields =>
      _managerRef.constraintFieldsMap;

  /// Validate constraints for fields that changed.
  ///
  /// Call this after updating fields to check constraints.
  /// Returns map of constraint name -> error message.
  Map<String, String> validateConstraints(Set<String> changedFields) =>
      _managerRef.validateConstraintsFor(this as T, changedFields);

  // ═══════════════════════════════════════════════════════════════════════════
  // Action Helpers
  // ═══════════════════════════════════════════════════════════════════════════

  /// Validate the record and throw [ValidationException] if invalid.
  void ensureValid({String? forAction}) {
    final errors = validate();
    if (errors.isNotEmpty) {
      throw ValidationException(errors, action: forAction);
    }
  }

  /// Call an Odoo action and return the refreshed record.
  Future<T> callActionAndRefresh(
    String odooMethod, {
    Map<String, dynamic>? kwargs,
  }) async {
    await callAction(odooMethod, kwargs: kwargs);
    return (await refresh()) ?? (this as T);
  }

  /// Execute a business action with validation.
  ///
  /// 1. Validates for the action
  /// 2. Checks state transition if applicable
  /// 3. Calls the Odoo action
  /// 4. Returns refreshed record
  ///
  /// ```dart
  /// final confirmed = await order.executeAction(
  ///   'confirm',
  ///   odooMethod: 'action_confirm',
  ///   targetState: 'sale',
  /// );
  /// ```
  Future<T> executeAction(
    String action, {
    required String odooMethod,
    String? targetState,
    Map<String, dynamic>? kwargs,
  }) async {
    // Validate
    ensureValid(forAction: action);

    // Check state transition
    if (targetState != null) {
      ensureCanTransitionTo(targetState);
    }

    // Call action
    return await callActionAndRefresh(odooMethod, kwargs: kwargs);
  }

  // ═══════════════════════════════════════════════════════════════════════════
  // Field Metadata
  // ═══════════════════════════════════════════════════════════════════════════

  /// Get list of all computed field names.
  List<String> get computedFields => _managerRef.computedFieldNames;

  /// Get list of all stored field names (for Drift).
  List<String> get storedFields => _managerRef.storedFieldNames;

  /// Get list of fields that should be sent to Odoo on save.
  List<String> get writableFields => _managerRef.writableFieldNames;

  /// Check if a field is computed.
  bool isComputedField(String field) => computedFields.contains(field);

  /// Check if a field has an onchange handler.
  bool hasOnchange(String field) => onchangeHandlers.containsKey(field);

  // ═══════════════════════════════════════════════════════════════════════════
  // Matrix Pattern - Configuration Access
  // ═══════════════════════════════════════════════════════════════════════════

  /// Get the model configuration.
  ///
  /// Override this getter to return your model's configuration.
  /// This is the core of the Matrix pattern - all model metadata in one place.
  SmartModelConfig? get modelConfig => SmartModelConfigRegistry.get<T>();

  /// Get the field registry for this model.
  FieldRegistry? get fieldRegistry {
    final config = modelConfig;
    if (config == null) return null;
    return config.toFieldRegistry();
  }

  /// Get the sync configuration.
  SyncConfig get syncConfig => modelConfig?.syncConfig ?? const SyncConfig();

  /// Get the Odoo model name.
  String get odooModelName => modelConfig?.odooModel ?? '';

  /// Get the local table name.
  String get tableName => modelConfig?.tableName ?? '';

  // ═══════════════════════════════════════════════════════════════════════════
  // Matrix Pattern - Computed Field Engine Integration
  // ═══════════════════════════════════════════════════════════════════════════

  /// Get the compute engine for this model.
  ComputedFieldEngine<T>? get computeEngine => ComputeEngineRegistry.get<T>();

  /// Recompute fields using the compute engine.
  ///
  /// This is the Matrix-aware version that uses the registered compute engine.
  T recomputeWithEngine(Set<String> changedFields) {
    final engine = computeEngine;
    if (engine == null) return recomputeAll(changedFields);
    return engine.recompute(this as T, changedFields);
  }

  /// Recompute all fields using the compute engine.
  T recomputeAllWithEngine() {
    final engine = computeEngine;
    if (engine == null) return recomputeAllFields();
    return engine.recomputeAll(this as T);
  }

  // ═══════════════════════════════════════════════════════════════════════════
  // Matrix Pattern - Field Introspection
  // ═══════════════════════════════════════════════════════════════════════════

  /// Get a field definition by name.
  FieldDefinition? getFieldDefinition(String fieldName) {
    return fieldRegistry?[fieldName];
  }

  /// Get all field definitions.
  Iterable<FieldDefinition> get allFieldDefinitions {
    return fieldRegistry?.all ?? [];
  }

  /// Get fields that should be sent to Odoo.
  List<String> get odooFieldNames {
    return fieldRegistry?.odooFieldNames ?? [];
  }

  /// Check if a field is required.
  bool isRequired(String fieldName) {
    return fieldRegistry?[fieldName]?.required ?? false;
  }

  /// Check if a field is readonly.
  bool isReadonly(String fieldName) {
    return fieldRegistry?[fieldName]?.readonly ?? false;
  }

  /// Get the field type.
  FieldType? getFieldType(String fieldName) {
    return fieldRegistry?[fieldName]?.type;
  }

  // ═══════════════════════════════════════════════════════════════════════════
  // Matrix Pattern - Validation with Field Definitions
  // ═══════════════════════════════════════════════════════════════════════════

  /// Validate all required fields.
  ///
  /// Returns map of field -> error message for missing required fields.
  Map<String, String> validateRequired() {
    final errors = <String, String>{};
    final registry = fieldRegistry;
    if (registry == null) return errors;

    for (final field in registry.required) {
      final value = _getFieldValue(field.name);
      if (value == null || (value is String && value.isEmpty)) {
        errors[field.name] = '${field.effectiveLabel} es requerido';
      }
    }

    return errors;
  }

  /// Get field value dynamically.
  /// Delegates to the manager's generated field accessor.
  dynamic _getFieldValue(String fieldName) =>
      _managerRef.getRecordFieldValue(this as T, fieldName);

  // ═══════════════════════════════════════════════════════════════════════════
  // Matrix Pattern - WebSocket Event Handling
  // ═══════════════════════════════════════════════════════════════════════════

  /// Apply changes from a WebSocket event.
  ///
  /// Delegates to manager's generated implementation.
  T applyWebSocketUpdate(Map<String, dynamic> changes) =>
      _managerRef.applyWebSocketChangesToRecord(this as T, changes);

  /// Check if this model should subscribe to WebSocket events.
  bool get shouldSubscribeWebSocket => syncConfig.subscribeWebSocket;
}

/// Extension to help with reactive updates in UI.
extension SmartOdooModelUIExtension<T extends SmartOdooModel<T>> on T {
  /// Create a builder for fluent field updates.
  ///
  /// ```dart
  /// final updated = order.edit()
  ///   .set('partnerId', newPartnerId)
  ///   .set('dateOrder', DateTime.now())
  ///   .build();
  /// ```
  SmartModelBuilder<T> edit() => SmartModelBuilder<T>(this);
}

/// Builder for fluent model updates.
class SmartModelBuilder<T extends SmartOdooModel<T>> {
  T _model;
  final Set<String> _changedFields = {};

  SmartModelBuilder(this._model);

  /// Set a field value.
  SmartModelBuilder<T> set(String field, dynamic value) {
    _model = _model.updateField(field, value);
    _changedFields.add(field);
    return this;
  }

  /// Build the final model with all updates applied.
  T build() {
    // Recompute all affected fields
    return _model.recomputeAll(_changedFields);
  }
}

/// Mixin for line models (sale.order.line, account.move.line, etc.)
///
/// Provides:
/// - Automatic recalculation of line amounts
/// - Link to parent record
/// - Sequence management
///
/// **Note:** This mixin is used with OdooRecord and SmartOdooModel.
///
/// Type parameters:
/// - T: The line model type (must be the same as the class using this mixin)
/// - P: The parent model type (optional, defaults to dynamic)
///
/// Example:
/// ```dart
/// @freezed
/// class SaleOrderLine with _$SaleOrderLine,
///     OdooRecord<SaleOrderLine>,
///     SmartOdooModel<SaleOrderLine>,
///     SmartOdooLine<SaleOrderLine, SaleOrder> {
///   // ...
/// }
/// ```
mixin SmartOdooLine<T extends OdooRecord<T>, P> {
  /// Reference to parent record ID.
  int? get parentId;

  /// Sequence number for ordering.
  int get sequence => 0;

  /// Check if this is a display-only line (section/note).
  bool get isDisplayLine => false;

  /// Recalculate line amounts after field changes.
  ///
  /// Typically called after quantity, price, or discount changes.
  ///
  /// ```dart
  /// final updated = line.recalculateAmounts();
  /// ```
  T recalculateAmounts() {
    // Default implementation - override in generated code
    return this as T;
  }

  /// Called when amounts change to notify parent.
  ///
  /// Override to implement specific amount calculation logic.
  /// [taxPercent] can be required or optional depending on implementation.
  ///
  /// ```dart
  /// @override
  /// T onAmountsChanged({
  ///   double? newPriceUnit,
  ///   double? newQuantity,
  ///   double? newDiscount,
  ///   required double taxPercent,
  /// }) {
  ///   final price = newPriceUnit ?? priceUnit;
  ///   final qty = newQuantity ?? productUomQty;
  ///   final disc = newDiscount ?? discount;
  ///
  ///   final subtotal = price * qty * (1 - disc / 100);
  ///   final tax = subtotal * taxPercent / 100;
  ///
  ///   return copyWith(
  ///     priceUnit: price,
  ///     productUomQty: qty,
  ///     discount: disc,
  ///     priceSubtotal: subtotal,
  ///     priceTax: tax,
  ///     priceTotal: subtotal + tax,
  ///   );
  /// }
  /// ```
  T onAmountsChanged({
    double? newPriceUnit,
    double? newQuantity,
    double? newDiscount,
    required double taxPercent,
  }) {
    return this as T;
  }
}

/// Registry for computed field methods.
///
/// Used by generated code to store compute method references.
class ComputeMethodRegistry {
  static final Map<Type, Map<String, Function>> _methods = {};

  /// Register a compute method for a model.
  static void register<T>(String field, Map<String, dynamic> Function() method) {
    _methods[T] ??= {};
    _methods[T]![field] = method;
  }

  /// Get compute method for a field.
  static Map<String, dynamic> Function()? get<T>(String field) {
    return _methods[T]?[field] as Map<String, dynamic> Function()?;
  }
}

/// Registry for onchange methods.
class OnchangeMethodRegistry {
  static final Map<Type, Map<String, Function>> _methods = {};

  /// Register an onchange method for a model.
  static void register<T>(String field, Function method) {
    _methods[T] ??= {};
    _methods[T]![field] = method;
  }

  /// Get onchange method for a field.
  static Function? get<T>(String field) {
    return _methods[T]?[field];
  }
}
